function dJ = jacobian_dot_project(in1,in2)
%JACOBIAN_DOT_PROJECT
%    dJ = JACOBIAN_DOT_PROJECT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2023 14:47:46

dq1 = in1(7,:);
dq2 = in1(8,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(3,:);
q2 = in1(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = q1+t2;
t4 = sin(t2);
t5 = q2+t3;
t6 = sin(t3);
t7 = l_AB.*t4;
t8 = sin(t5);
t9 = l_BC.*t6;
t10 = l_CD.*t8;
t11 = dq2.*t10;
t13 = t9+t10;
t12 = -t11;
t14 = dq1.*t13;
t16 = t7+t13;
t15 = -t14;
t17 = dth2.*t16;
t18 = -t17;
dJ = reshape([t12+t15+t18-dth1.*(t16+l_OA.*sin(th1)),0.0,t12+t15+t18-dth1.*t16,0.0],[2,2]);
