function J = jacobian_project(in1,in2)
%JACOBIAN_PROJECT
%    J = JACOBIAN_PROJECT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2023 14:47:45

l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(3,:);
q2 = in1(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = q1+t2;
t5 = cos(t4);
t6 = q2+t4;
t7 = l_AB.*t3;
t8 = cos(t6);
t9 = l_BC.*t5;
t10 = l_CD.*t8;
J = reshape([t7+t9+t10+l_OA.*cos(th1),0.0,t7+t9+t10,0.0],[2,2]);
