function Grav_Joint_Sp = Grav_project(in1,in2)
%Grav_project
%    Grav_Joint_Sp = Grav_project(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2023 14:47:48

g = in2(19,:);
l_AB = in2(2,:);
l_Amb = in2(6,:);
l_BC = in2(3,:);
l_Bm1 = in2(7,:);
l_Cm2 = in2(8,:);
l_OA = in2(1,:);
l_Omp = in2(5,:);
m1 = in2(11,:);
m2 = in2(12,:);
mb = in2(10,:);
mp = in2(9,:);
q1 = in1(3,:);
q2 = in1(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = sin(th1);
t3 = th1+th2;
t4 = l_OA.*t2;
t5 = q1+t3;
t6 = sin(t3);
t7 = q2+t5;
t8 = sin(t5);
t9 = l_AB.*t6;
t10 = sin(t7);
t11 = l_BC.*t8;
t12 = l_Bm1.*t8;
t13 = l_Cm2.*t10;
Grav_Joint_Sp = [g.*mb.*(t4+l_Amb.*t6)+g.*m2.*(t4+t9+t11+t13)+g.*m1.*(t4+t9+t12)+g.*l_Omp.*mp.*t2;g.*m1.*(t9+t12)+g.*m2.*(t9+t11+t13)+g.*l_Amb.*mb.*t6;g.*m2.*(t11+t13)+g.*m1.*t12;g.*m2.*t13];
