function rD = position_foot(in1,in2)
%POSITION_FOOT
%    rD = POSITION_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2023 14:47:44

l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(3,:);
q2 = in1(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = q1+t2;
t4 = q2+t3;
rD = [l_AB.*sin(t2)+l_BC.*sin(t3)+l_CD.*sin(t4)+l_OA.*sin(th1);-l_AB.*cos(t2)-l_BC.*cos(t3)-l_CD.*cos(t4)-l_OA.*cos(th1)];
