function drD = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    drD = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    01-Nov-2023 14:47:44

dq1 = in1(7,:);
dq2 = in1(8,:);
dth1 = in1(5,:);
dth2 = in1(6,:);
l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(3,:);
q2 = in1(4,:);
th1 = in1(1,:);
th2 = in1(2,:);
t2 = th1+th2;
t3 = cos(t2);
t4 = q1+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = q2+t4;
t8 = sin(t4);
t9 = l_AB.*t3;
t10 = l_AB.*t5;
t11 = cos(t7);
t12 = sin(t7);
t13 = l_BC.*t6;
t14 = l_BC.*t8;
t15 = l_CD.*t11;
t16 = l_CD.*t12;
drD = [dq1.*(t13+t15)+dth1.*(t9+t13+t15+l_OA.*cos(th1))+dq2.*t15+dth2.*(t9+t13+t15);dq1.*(t14+t16)+dth1.*(t10+t14+t16+l_OA.*sin(th1))+dq2.*t16+dth2.*(t10+t14+t16)];
