function b = b_foot(in1,in2,in3)
%B_FOOT
%    B = B_FOOT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:03:32

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
g = in3(19,:);
l_AB = in3(2,:);
l_Amb = in3(6,:);
l_BC = in3(3,:);
l_Bm1 = in3(7,:);
l_Cm2 = in3(8,:);
l_OA = in3(1,:);
l_Omp = in3(5,:);
m1 = in3(11,:);
m2 = in3(12,:);
mb = in3(10,:);
mp = in3(9,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
tau1 = in2(1,:);
tau2 = in2(2,:);
t2 = sin(q1);
t3 = sin(q2);
t4 = sin(q3);
t5 = q1+q2;
t6 = q2+q3;
t7 = dq1.^2;
t8 = dq2.^2;
t9 = dq3.^2;
t10 = q3+t5;
t11 = sin(t5);
t12 = sin(t6);
t16 = l_BC.*l_Cm2.*m2.*t4.*t9;
t17 = dq1.*dq3.*l_BC.*l_Cm2.*m2.*t4.*2.0;
t18 = dq2.*dq3.*l_BC.*l_Cm2.*m2.*t4.*2.0;
t13 = sin(t10);
t14 = g.*l_BC.*m2.*t11;
t15 = g.*l_Bm1.*m1.*t11;
t22 = l_AB.*l_Cm2.*m2.*t7.*t12;
t23 = l_Cm2.*l_OA.*m2.*t7.*t12;
t19 = g.*l_Cm2.*m2.*t13;
t20 = -t14;
t21 = -t15;
t25 = -t22;
t26 = -t23;
t24 = -t19;
mt1 = [t16+t17+t18+t20+t21+t24-g.*l_AB.*m1.*t2-g.*l_AB.*m2.*t2-g.*l_OA.*m1.*t2-g.*l_OA.*m2.*t2-g.*l_Amb.*mb.*t2-g.*l_OA.*mb.*t2-g.*l_Omp.*mp.*t2+l_AB.*l_BC.*m2.*t3.*t8+l_AB.*l_Bm1.*m1.*t3.*t8+l_AB.*l_Cm2.*m2.*t8.*t12+l_AB.*l_Cm2.*m2.*t9.*t12+l_BC.*l_OA.*m2.*t3.*t8+l_Bm1.*l_OA.*m1.*t3.*t8+l_Cm2.*l_OA.*m2.*t8.*t12+l_Cm2.*l_OA.*m2.*t9.*t12+dq1.*dq2.*l_AB.*l_BC.*m2.*t3.*2.0+dq1.*dq2.*l_AB.*l_Bm1.*m1.*t3.*2.0+dq1.*dq2.*l_AB.*l_Cm2.*m2.*t12.*2.0+dq1.*dq3.*l_AB.*l_Cm2.*m2.*t12.*2.0+dq2.*dq3.*l_AB.*l_Cm2.*m2.*t12.*2.0+dq1.*dq2.*l_BC.*l_OA.*m2.*t3.*2.0+dq1.*dq2.*l_Bm1.*l_OA.*m1.*t3.*2.0+dq1.*dq2.*l_Cm2.*l_OA.*m2.*t12.*2.0+dq1.*dq3.*l_Cm2.*l_OA.*m2.*t12.*2.0+dq2.*dq3.*l_Cm2.*l_OA.*m2.*t12.*2.0];
mt2 = [t16+t17+t18+t20+t21+t24+t25+t26+tau1-l_AB.*l_BC.*m2.*t3.*t7-l_AB.*l_Bm1.*m1.*t3.*t7-l_BC.*l_OA.*m2.*t3.*t7-l_Bm1.*l_OA.*m1.*t3.*t7;t24+t25+t26+tau2-l_BC.*l_Cm2.*m2.*t4.*t7-l_BC.*l_Cm2.*m2.*t4.*t8-dq1.*dq2.*l_BC.*l_Cm2.*m2.*t4.*2.0];
b = [mt1;mt2];
