function Corr_Joint_Sp = Corr_foot_and_arm(in1,in2)
%Corr_foot_and_arm
%    Corr_Joint_Sp = Corr_foot_and_arm(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Nov-2023 13:39:03

dq1 = in1(5,:);
dq2 = in1(6,:);
dq3 = in1(7,:);
dq4 = in1(8,:);
l_AB = in2(2,:);
l_Am3 = in2(10,:);
l_BC = in2(3,:);
l_Bm1 = in2(8,:);
l_Cm2 = in2(9,:);
l_OA = in2(1,:);
m1 = in2(13,:);
m2 = in2(14,:);
m3 = in2(15,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = sin(q2);
t3 = sin(q3);
t4 = sin(q4);
t5 = q2+q3;
t6 = dq1.^2;
t7 = dq2.^2;
t8 = dq3.^2;
t9 = sin(t5);
t10 = l_BC.*l_Cm2.*m2.*t3.*t8;
t11 = dq1.*dq3.*l_BC.*l_Cm2.*m2.*t3.*2.0;
t12 = dq2.*dq3.*l_BC.*l_Cm2.*m2.*t3.*2.0;
t13 = -t11;
t14 = -t12;
t15 = -t10;
mt1 = [t13+t14+t15-l_AB.*l_BC.*m2.*t2.*t7-l_AB.*l_Bm1.*m1.*t2.*t7-l_AB.*l_Cm2.*m2.*t7.*t9-l_AB.*l_Cm2.*m2.*t8.*t9-l_BC.*l_OA.*m2.*t2.*t7-l_Bm1.*l_OA.*m1.*t2.*t7-l_Cm2.*l_OA.*m2.*t7.*t9-l_Cm2.*l_OA.*m2.*t8.*t9-dq4.^2.*l_Am3.*l_OA.*m3.*t4-dq1.*dq2.*l_AB.*l_BC.*m2.*t2.*2.0-dq1.*dq2.*l_AB.*l_Bm1.*m1.*t2.*2.0-dq1.*dq2.*l_AB.*l_Cm2.*m2.*t9.*2.0-dq1.*dq3.*l_AB.*l_Cm2.*m2.*t9.*2.0-dq2.*dq3.*l_AB.*l_Cm2.*m2.*t9.*2.0-dq1.*dq4.*l_Am3.*l_OA.*m3.*t4.*2.0-dq1.*dq2.*l_BC.*l_OA.*m2.*t2.*2.0-dq1.*dq2.*l_Bm1.*l_OA.*m1.*t2.*2.0-dq1.*dq2.*l_Cm2.*l_OA.*m2.*t9.*2.0-dq1.*dq3.*l_Cm2.*l_OA.*m2.*t9.*2.0-dq2.*dq3.*l_Cm2.*l_OA.*m2.*t9.*2.0];
mt2 = [t13+t14+t15+l_AB.*l_BC.*m2.*t2.*t6+l_AB.*l_Bm1.*m1.*t2.*t6+l_AB.*l_Cm2.*m2.*t6.*t9+l_BC.*l_OA.*m2.*t2.*t6+l_Bm1.*l_OA.*m1.*t2.*t6+l_Cm2.*l_OA.*m2.*t6.*t9;l_Cm2.*m2.*(l_AB.*t6.*t9+l_BC.*t3.*t6+l_BC.*t3.*t7+l_OA.*t6.*t9+dq1.*dq2.*l_BC.*t3.*2.0);l_Am3.*l_OA.*m3.*t4.*t6];
Corr_Joint_Sp = [mt1;mt2];
