function Grav_Joint_Sp = Grav_foot(in1,in2)
%Grav_foot
%    Grav_Joint_Sp = Grav_foot(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:03:42

g = in2(19,:);
l_AB = in2(2,:);
l_Amb = in2(6,:);
l_BC = in2(3,:);
l_Bm1 = in2(7,:);
l_Cm2 = in2(8,:);
l_OA = in2(1,:);
l_Omp = in2(5,:);
m1 = in2(11,:);
m2 = in2(12,:);
mb = in2(10,:);
mp = in2(9,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q1);
t3 = q1+q2;
t4 = l_AB.*t2;
t5 = l_OA.*t2;
t6 = q3+t3;
t7 = sin(t3);
t8 = sin(t6);
t9 = l_BC.*t7;
t10 = l_Cm2.*t8;
Grav_Joint_Sp = [g.*m2.*(t4+t5+t9+t10)+g.*m1.*(t4+t5+l_Bm1.*t7)+g.*l_Omp.*mp.*t2+g.*mb.*t2.*(l_Amb+l_OA);g.*m2.*(t9+t10)+g.*l_Bm1.*m1.*t7;g.*m2.*t10];
