function Grav_Joint_Sp = Grav_foot_and_arm(in1,in2)
%Grav_foot_and_arm
%    Grav_Joint_Sp = Grav_foot_and_arm(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Nov-2023 13:39:03

g = in2(23,:);
l_AB = in2(2,:);
l_Am3 = in2(10,:);
l_Amb = in2(7,:);
l_BC = in2(3,:);
l_Bm1 = in2(8,:);
l_Cm2 = in2(9,:);
l_OA = in2(1,:);
l_Omp = in2(6,:);
m1 = in2(13,:);
m2 = in2(14,:);
m3 = in2(15,:);
mb = in2(12,:);
mp = in2(11,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = sin(q1);
t3 = q1+q2;
t4 = q1+q4;
t5 = l_AB.*t2;
t6 = l_OA.*t2;
t7 = q3+t3;
t8 = sin(t3);
t9 = sin(t4);
t10 = sin(t7);
t11 = l_BC.*t8;
t12 = l_Cm2.*t10;
Grav_Joint_Sp = [g.*m3.*(t6+l_Am3.*t9)+g.*m2.*(t5+t6+t11+t12)+g.*m1.*(t5+t6+l_Bm1.*t8)+g.*l_Omp.*mp.*t2+g.*mb.*t2.*(l_Amb+l_OA);g.*m2.*(t11+t12)+g.*l_Bm1.*m1.*t8;g.*m2.*t12;g.*l_Am3.*m3.*t9];
