function dJ = jacobian_dot_foot_and_arm(in1,in2)
%JACOBIAN_DOT_FOOT_AND_ARM
%    dJ = JACOBIAN_DOT_FOOT_AND_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Nov-2023 13:39:01

dq1 = in1(5,:);
dq2 = in1(6,:);
dq3 = in1(7,:);
l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = sin(q1);
t3 = q1+q2;
t4 = q3+t3;
t5 = sin(t3);
t6 = sin(t4);
t7 = l_BC.*t5;
t8 = l_CD.*t6;
t9 = dq3.*t8;
t11 = t7+t8;
t10 = -t9;
t12 = dq2.*t11;
t13 = -t12;
dJ = reshape([t10+t13-dq1.*(t11+l_AB.*t2+l_OA.*t2),0.0,t10+t13-dq1.*t11,0.0],[2,2]);
