function dJ = jacobian_dot_foot(in1,in2)
%JACOBIAN_DOT_FOOT
%    dJ = JACOBIAN_DOT_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:03:39

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2+q3;
t3 = sin(t2);
t4 = dq2.*l_CD.*t3;
t5 = dq3.*l_CD.*t3;
t6 = -t4;
t7 = -t5;
dJ = reshape([t6+t7-dq1.*(l_CD.*t3+l_OA.*sin(q1)),0.0,t6+t7-dq1.*l_CD.*t3,0.0],[2,2]);
