function keypoints = keypoints_foot(in1,in2)
%KEYPOINTS_FOOT
%    KEYPOINTS = KEYPOINTS_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:03:43

l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = l_AB.*t2;
t6 = l_OA.*t2;
t7 = l_AB.*t3;
t8 = l_OA.*t3;
t9 = q3+t4;
t10 = -t5;
t11 = -t6;
keypoints = reshape([t8,t11,t7+t8,t10+t11,t7+t8+l_BC.*sin(t4),t10+t11-l_BC.*cos(t4),t8+l_CD.*sin(t9),t11-l_CD.*cos(t9)],[2,4]);
