function keypoints = keypoints_foot_and_arm(in1,in2)
%KEYPOINTS_FOOT_AND_ARM
%    KEYPOINTS = KEYPOINTS_FOOT_AND_ARM(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    14-Nov-2023 13:39:04

l_AB = in2(2,:);
l_AE = in2(5,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = q1+q4;
t6 = l_AB.*t2;
t7 = l_OA.*t2;
t8 = cos(t4);
t9 = l_AB.*t3;
t10 = l_OA.*t3;
t11 = q3+t4;
t12 = sin(t4);
t13 = l_BC.*t8;
t14 = l_BC.*t12;
t15 = -t6;
t16 = -t7;
t17 = -t13;
keypoints = reshape([t10,t16,t9+t10,t15+t16,t9+t10+t14,t15+t16+t17,t9+t10+t14+l_CD.*sin(t11),t15+t16+t17-l_CD.*cos(t11),t10+l_AE.*sin(t5),t16-l_AE.*cos(t5)],[2,5]);
