function keypoints = keypoints_foot(in1,in2)
%KEYPOINTS_FOOT
%    KEYPOINTS = KEYPOINTS_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:49:02

l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = cos(q1);
t3 = sin(q1);
t4 = q1+q2;
t5 = l_AB.*t2;
t6 = l_OA.*t2;
t7 = cos(t4);
t8 = l_AB.*t3;
t9 = l_OA.*t3;
t10 = q3+t4;
t11 = sin(t4);
t12 = l_BC.*t7;
t13 = l_BC.*t11;
t14 = -t5;
t15 = -t6;
t16 = -t12;
keypoints = reshape([t9,t15,t8+t9,t14+t15,t8+t9+t13,t14+t15+t16,t8+t9+t13+l_CD.*sin(t10),t14+t15+t16-l_CD.*cos(t10)],[2,4]);
