function rD = position_foot(in1,in2)
%POSITION_FOOT
%    rD = POSITION_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:03:35

l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2+q3;
rD = [l_OA.*sin(q1)+l_CD.*sin(t2);-l_OA.*cos(q1)-l_CD.*cos(t2)];
