function rD = position_foot(in1,in2)
%POSITION_FOOT
%    rD = POSITION_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Nov-2023 12:58:14

l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1+q2;
t3 = q3+t2;
t4 = q4+t3;
rD = [l_OA.*sin(q1)+l_AB.*sin(t2)+l_BC.*sin(t3)+l_CD.*sin(t4);-l_OA.*cos(q1)-l_AB.*cos(t2)-l_BC.*cos(t3)-l_CD.*cos(t4)];
