function drD = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    drD = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    09-Nov-2023 09:03:37

dq1 = in1(4,:);
dq2 = in1(5,:);
dq3 = in1(6,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
t2 = q1+q2+q3;
t3 = cos(t2);
t4 = sin(t2);
drD = [dq1.*(l_CD.*t3+l_OA.*cos(q1))+dq2.*l_CD.*t3+dq3.*l_CD.*t3;dq1.*(l_CD.*t4+l_OA.*sin(q1))+dq2.*l_CD.*t4+dq3.*l_CD.*t4];
