function drD = velocity_foot(in1,in2)
%VELOCITY_FOOT
%    drD = VELOCITY_FOOT(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    07-Nov-2023 12:58:14

dq1 = in1(5,:);
dq2 = in1(6,:);
dq3 = in1(7,:);
dq4 = in1(8,:);
l_AB = in2(2,:);
l_BC = in2(3,:);
l_CD = in2(4,:);
l_OA = in2(1,:);
q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q4 = in1(4,:);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = sin(t2);
t6 = cos(t4);
t7 = q4+t4;
t8 = sin(t4);
t9 = l_AB.*t3;
t10 = l_AB.*t5;
t11 = cos(t7);
t12 = sin(t7);
t13 = l_BC.*t6;
t14 = l_BC.*t8;
t15 = l_CD.*t11;
t16 = l_CD.*t12;
drD = [dq3.*(t13+t15)+dq1.*(t9+t13+t15+l_OA.*cos(q1))+dq4.*t15+dq2.*(t9+t13+t15);dq3.*(t14+t16)+dq1.*(t10+t14+t16+l_OA.*sin(q1))+dq4.*t16+dq2.*(t10+t14+t16)];
